### PR TITLE
Adds LICENCE

### PR DESCRIPTION
**Pull request by gislikonrad**
Issue #4

### CODE REVIEW

**Comment by jorge-sanz** [comment]
LGTM 👍 🙂

Thanks! @gislikonrad

**Comment by javierprovecho** [comment]
@gislikonrad you should update the [`package.json` @ line 26](https://github.com/gislikonrad/swangular-components/blob/master/package.json#L26) referencing [this same license string](https://gist.github.com/robertkowalski/7620849#file-npm-registry-licenses-txt-L22) for coherence, unless you want to distribute through npm with another license, thats up to you 😉

**Comment by jorge-sanz** [comment]
👀 👌 @javierprovecho

**Comment by gislikonrad** [comment]
I've added Unlicence to the package.json

**Pull request merged**
